-- Tables for the private AI proxy (/api/ai, see workers/ai_proxy.js).
-- Idempotent; apply with:
--   npx wrangler d1 execute nathanpenny --remote --file workers/schema.sql

-- Bearer keys for /api/ai. Only the SHA-256 hash of each key is stored;
-- plaintext keys are generated by tools/ai_key.py and kept by the owner.
-- monthly_limit NULL = unlimited (avoid — a leaked key would burn upstream
-- credit without a cap; prefer a concrete number).
CREATE TABLE IF NOT EXISTS api_keys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  key_hash TEXT NOT NULL UNIQUE,
  monthly_limit INTEGER,
  enabled INTEGER NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  last_used_at DATETIME
);

-- Monthly request counters backing the quota breaker (single-roundtrip
-- conditional upsert in ai_proxy.js). month is 'YYYY-MM' in UTC.
CREATE TABLE IF NOT EXISTS ai_usage (
  key_id INTEGER NOT NULL,
  month TEXT NOT NULL,
  requests INTEGER NOT NULL DEFAULT 0,
  tokens_in INTEGER NOT NULL DEFAULT 0,
  tokens_out INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (key_id, month)
);

-- One row per chat completion call. Metadata only — never prompt or
-- response content. Written via ctx.waitUntil, so log failures cannot
-- affect the response.
CREATE TABLE IF NOT EXISTS ai_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key_id INTEGER NOT NULL,
  model TEXT NOT NULL,
  provider TEXT NOT NULL,
  status INTEGER NOT NULL,
  stream INTEGER NOT NULL DEFAULT 0,
  tokens_in INTEGER,
  tokens_out INTEGER,
  latency_ms INTEGER,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ai_logs_created ON ai_logs (created_at);

-- Tables for the comment feature (created manually in prod 2026-07; DDL
-- dumped verbatim from prod via sqlite_master, wrapped in IF NOT EXISTS so
-- this file can recreate the whole database from scratch).
CREATE TABLE IF NOT EXISTS comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Per-IP sliding-window counters backing POST /comments rate limiting
-- (window-aligned upsert in comments.js). window_start is epoch seconds.
CREATE TABLE IF NOT EXISTS comment_rate (
  ip TEXT NOT NULL,
  window_start INTEGER NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (ip, window_start)
);

-- Same shape as comment_rate, but for the public site avatar chat
-- (POST /api/site-chat) so comment and chat budgets stay independent.
CREATE TABLE IF NOT EXISTS chat_rate (
  ip TEXT NOT NULL,
  window_start INTEGER NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (ip, window_start)
);
