-- Tables for the private AI proxy (/api/ai, see workers/ai_proxy.js).
-- Idempotent; apply with:
--   npx wrangler d1 execute nathanpenny --remote --file workers/schema.sql

-- Bearer keys for /api/ai. Only the SHA-256 hash of each key is stored;
-- plaintext keys are generated by tools/ai_key.py and kept by the owner.
-- monthly_limit NULL = unlimited (avoid — a leaked key would burn upstream
-- credit without a cap; prefer a concrete number).
CREATE TABLE IF NOT EXISTS api_keys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  key_hash TEXT NOT NULL UNIQUE,
  monthly_limit INTEGER,
  enabled INTEGER NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  last_used_at DATETIME
);

-- Monthly request counters backing the quota breaker (single-roundtrip
-- conditional upsert in ai_proxy.js). month is 'YYYY-MM' in UTC.
CREATE TABLE IF NOT EXISTS ai_usage (
  key_id INTEGER NOT NULL,
  month TEXT NOT NULL,
  requests INTEGER NOT NULL DEFAULT 0,
  tokens_in INTEGER NOT NULL DEFAULT 0,
  tokens_out INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (key_id, month)
);

-- One row per chat completion call. Metadata only — never prompt or
-- response content. Written via ctx.waitUntil, so log failures cannot
-- affect the response.
CREATE TABLE IF NOT EXISTS ai_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key_id INTEGER NOT NULL,
  model TEXT NOT NULL,
  provider TEXT NOT NULL,
  status INTEGER NOT NULL,
  stream INTEGER NOT NULL DEFAULT 0,
  tokens_in INTEGER,
  tokens_out INTEGER,
  latency_ms INTEGER,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ai_logs_created ON ai_logs (created_at);

-- Tables for the comment feature (created manually in prod 2026-07; DDL
-- dumped verbatim from prod via sqlite_master, wrapped in IF NOT EXISTS so
-- this file can recreate the whole database from scratch). ip_hash is the
-- salted one-way hash of the commenter's IP (moderation below) — the
-- address itself is never stored. Existing prod databases were migrated with:
--   ALTER TABLE comments ADD COLUMN ip_hash TEXT NOT NULL DEFAULT '';
CREATE TABLE IF NOT EXISTS comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  content TEXT NOT NULL,
  ip_hash TEXT NOT NULL DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Per-IP sliding-window counters backing POST /comments rate limiting
-- (window-aligned upsert in comments.js). window_start is epoch seconds.
CREATE TABLE IF NOT EXISTS comment_rate (
  ip TEXT NOT NULL,
  window_start INTEGER NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (ip, window_start)
);

-- Same shape as comment_rate, but for the public site avatar chat
-- (POST /api/site-chat) so comment and chat budgets stay independent.
CREATE TABLE IF NOT EXISTS chat_rate (
  ip TEXT NOT NULL,
  window_start INTEGER NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (ip, window_start)
);

-- Tables for the first-party analytics (see workers/analytics.js). Bots are
-- dropped at ingest, `date` is the UTC+8 day of the hit, and visitor_id is a
-- pseudonymous salted hash of IP + UA — the IP itself is never stored.
-- Raw rows are pruned by the nightly cron after 13 months.
CREATE TABLE IF NOT EXISTS analytics_hits (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ts INTEGER NOT NULL,               -- epoch seconds of the pageview
  date TEXT NOT NULL,                -- 'YYYY-MM-DD' in UTC+8
  visit_id TEXT NOT NULL,            -- client session id (sessionStorage uuid)
  visitor_id TEXT NOT NULL,          -- pseudonymous visitor hash
  depth INTEGER NOT NULL DEFAULT 1,  -- pageview index within the session
  path TEXT NOT NULL,
  ref_host TEXT NOT NULL DEFAULT '', -- '' = direct/internal
  ref_path TEXT NOT NULL DEFAULT '',
  ref_kind TEXT NOT NULL DEFAULT 'direct', -- direct|search|social|other
  country TEXT NOT NULL DEFAULT '',  -- request.cf.country (ISO 3166-1 alpha-2)
  device TEXT NOT NULL DEFAULT '',   -- desktop|mobile|tablet
  browser TEXT NOT NULL DEFAULT '',
  os TEXT NOT NULL DEFAULT '',
  lang TEXT NOT NULL DEFAULT '',
  tz TEXT NOT NULL DEFAULT '',
  duration INTEGER NOT NULL DEFAULT 0, -- seconds, backfilled by the duration beacon
  is_self INTEGER NOT NULL DEFAULT 0  -- the owner's own visits (excludable in stats)
);
CREATE INDEX IF NOT EXISTS idx_analytics_hits_date ON analytics_hits (date);
CREATE INDEX IF NOT EXISTS idx_analytics_hits_visitor ON analytics_hits (visitor_id, id);
CREATE INDEX IF NOT EXISTS idx_analytics_hits_visit ON analytics_hits (visit_id);

-- One row per browsing session (a tab), upserted on every pageview so the
-- sessions / bounce / entry-exit views need no GROUP BY over raw hits.
CREATE TABLE IF NOT EXISTS analytics_visits (
  visit_id TEXT PRIMARY KEY,
  visitor_id TEXT NOT NULL,
  start_ts INTEGER NOT NULL,
  last_ts INTEGER NOT NULL,
  hits INTEGER NOT NULL DEFAULT 1,
  entry_path TEXT NOT NULL,
  exit_path TEXT NOT NULL,
  ref_host TEXT NOT NULL DEFAULT '',
  ref_kind TEXT NOT NULL DEFAULT 'direct',
  country TEXT NOT NULL DEFAULT '',
  device TEXT NOT NULL DEFAULT '',
  is_self INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_analytics_visits_visitor ON analytics_visits (visitor_id, start_ts);

-- One row per pseudonymous visitor: the per-people profile the stats tab's
-- visitor list and drill-down read. sessions is maintained by the ingest
-- batch (incremented only when the visit_id is genuinely new).
CREATE TABLE IF NOT EXISTS analytics_visitors (
  visitor_id TEXT PRIMARY KEY,
  first_seen INTEGER NOT NULL,
  last_seen INTEGER NOT NULL,
  first_date TEXT NOT NULL,
  last_date TEXT NOT NULL,
  hits INTEGER NOT NULL DEFAULT 0,
  sessions INTEGER NOT NULL DEFAULT 0,
  last_path TEXT NOT NULL DEFAULT '',
  last_ref TEXT NOT NULL DEFAULT '',
  country TEXT NOT NULL DEFAULT '',
  device TEXT NOT NULL DEFAULT '',
  browser TEXT NOT NULL DEFAULT '',
  os TEXT NOT NULL DEFAULT '',
  lang TEXT NOT NULL DEFAULT '',
  tz TEXT NOT NULL DEFAULT '',
  is_self INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_analytics_visitors_last ON analytics_visitors (last_seen);

-- Per-IP ingest limiter for POST /api/analytics/hit (same shape as
-- comment_rate; the shared bumpRateWindow in comments.js does the counting).
CREATE TABLE IF NOT EXISTS analytics_rate (
  ip TEXT NOT NULL,
  window_start INTEGER NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (ip, window_start)
);

-- Comment moderation (workers/moderation.js): the admin blocklist. ip_hash
-- is the salted one-way hash of the commenter's IP (same ANALYTICS_SALT
-- secret as the analytics visitor hash) — the IP itself is never stored, and
-- POST /comments rejects senders whose hash is listed here.
CREATE TABLE IF NOT EXISTS banned_ips (
  ip_hash TEXT PRIMARY KEY,
  note TEXT NOT NULL DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 写作台 drafts (workers/drafts.js): form metadata + markdown body held in
-- D1 until published — deliberately NOT in the public repo, and not in the
-- publicly-readable R2 bucket. publish_at is an epoch-seconds schedule; the
-- 15-min cron publishes due drafts through the editor's GitHub path and
-- deletes the row on success.
CREATE TABLE IF NOT EXISTS drafts (
  slug TEXT PRIMARY KEY,
  meta TEXT NOT NULL,               -- JSON: {title,date,category,tags,description}
  body TEXT NOT NULL,
  publish_at INTEGER,               -- epoch seconds; NULL = plain draft
  updated_at INTEGER NOT NULL
);
