-- Tables for the private AI proxy (/api/ai, see workers/ai_proxy.js).
-- Idempotent; apply with:
--   npx wrangler d1 execute nathanpenny --remote --file workers/schema.sql

-- Bearer keys for /api/ai. Only the SHA-256 hash of each key is stored;
-- plaintext keys are generated by tools/ai_key.py and kept by the owner.
-- monthly_limit NULL = unlimited (avoid — a leaked key would burn upstream
-- credit without a cap; prefer a concrete number).
CREATE TABLE IF NOT EXISTS api_keys (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  key_hash TEXT NOT NULL UNIQUE,
  monthly_limit INTEGER,
  enabled INTEGER NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  last_used_at DATETIME
);

-- Monthly request counters backing the quota breaker (single-roundtrip
-- conditional upsert in ai_proxy.js). month is 'YYYY-MM' in UTC.
CREATE TABLE IF NOT EXISTS ai_usage (
  key_id INTEGER NOT NULL,
  month TEXT NOT NULL,
  requests INTEGER NOT NULL DEFAULT 0,
  tokens_in INTEGER NOT NULL DEFAULT 0,
  tokens_out INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (key_id, month)
);

-- One row per chat completion call. Metadata only — never prompt or
-- response content. Written via ctx.waitUntil, so log failures cannot
-- affect the response.
CREATE TABLE IF NOT EXISTS ai_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key_id INTEGER NOT NULL,
  model TEXT NOT NULL,
  provider TEXT NOT NULL,
  status INTEGER NOT NULL,
  stream INTEGER NOT NULL DEFAULT 0,
  tokens_in INTEGER,
  tokens_out INTEGER,
  latency_ms INTEGER,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ai_logs_created ON ai_logs (created_at);
